### ISSUE TITLE
Добавить кнопку "просмотреть идущие турниры"

### ISSUE THREAD

**Issue by Defenx** [Defenx/table-tennis-rating-system#27]
На странице /home добавить кнопку для всех ролей для просмотра идущих турниров (те, которые в статусе PROCESSING)

**Comment by Toxaencom1** [comment]
Я уже сделал в ветке runTournament, и она даже работает, перекидывает на страничку где все турниры в процессе, сервлет прилагается, только код сырой. (с магическими строками, CSS нету для этой странички)
